package com.wuyou.user.data.local.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.wuyou.user.data.local.db.EosAccount;
import com.wuyou.user.data.local.db.SearchHistoryBean;
import com.wuyou.user.data.local.db.UserInfo;

import com.wuyou.user.data.local.db.EosAccountDao;
import com.wuyou.user.data.local.db.SearchHistoryBeanDao;
import com.wuyou.user.data.local.db.UserInfoDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig eosAccountDaoConfig;
    private final DaoConfig searchHistoryBeanDaoConfig;
    private final DaoConfig userInfoDaoConfig;

    private final EosAccountDao eosAccountDao;
    private final SearchHistoryBeanDao searchHistoryBeanDao;
    private final UserInfoDao userInfoDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        eosAccountDaoConfig = daoConfigMap.get(EosAccountDao.class).clone();
        eosAccountDaoConfig.initIdentityScope(type);

        searchHistoryBeanDaoConfig = daoConfigMap.get(SearchHistoryBeanDao.class).clone();
        searchHistoryBeanDaoConfig.initIdentityScope(type);

        userInfoDaoConfig = daoConfigMap.get(UserInfoDao.class).clone();
        userInfoDaoConfig.initIdentityScope(type);

        eosAccountDao = new EosAccountDao(eosAccountDaoConfig, this);
        searchHistoryBeanDao = new SearchHistoryBeanDao(searchHistoryBeanDaoConfig, this);
        userInfoDao = new UserInfoDao(userInfoDaoConfig, this);

        registerDao(EosAccount.class, eosAccountDao);
        registerDao(SearchHistoryBean.class, searchHistoryBeanDao);
        registerDao(UserInfo.class, userInfoDao);
    }
    
    public void clear() {
        eosAccountDaoConfig.clearIdentityScope();
        searchHistoryBeanDaoConfig.clearIdentityScope();
        userInfoDaoConfig.clearIdentityScope();
    }

    public EosAccountDao getEosAccountDao() {
        return eosAccountDao;
    }

    public SearchHistoryBeanDao getSearchHistoryBeanDao() {
        return searchHistoryBeanDao;
    }

    public UserInfoDao getUserInfoDao() {
        return userInfoDao;
    }

}
